@echo off
echo Open Watcom Build Environment
SET WATCOM=%~dp0
PATH %WATCOM%\BINNT64;%WATCOM%\BINNT;%PATH%
SET INCLUDE=%WATCOM%\H;%WATCOM%\H\NT;%WATCOM%\H\NT\DIRECTX;%WATCOM%\H\NT\DDK;%INCLUDE%
SET EDPATH=%WATCOM%\EDDAT
SET WHTMLHELP=%WATCOM%\BINNT\HELP
SET WIPFC=%WATCOM%\WIPFC
